# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0002_auto_20160407_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
